In [1]:
# Importing Packages 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#importing dataset and viewing
dataset=pd.read_csv('Data@anz_new.csv')
dataset.head()

customer_id  card_present_flag  merchant_code       balance  age  \
0  CUS-1005756958           0.812500              0   2275.852055   53   
1  CUS-1117979751           0.826923              0   9829.929000   21   
2  CUS-1140341822           0.815385              0   5699.212250   28   
3  CUS-1147642491           0.750000              0   9032.841186   34   
4  CUS-1196156254           0.785276              0  22272.433760   34   

       amount  annual_salary  
0  222.862603            970  
1  339.843700           3578  
2  212.632500           1916  
3  245.600169           1711  
4  147.145796           3903

In [3]:
#Assigning dependent and independent variables
X = dataset.iloc[:, [4,5,6]].values
y = dataset.iloc[:, -1].values

In [20]:
print(X)

[[  53.          222.8626027   970.        ]
 [  21.          339.8437     3578.        ]
 [  28.          212.6325     1916.        ]
 [  34.          245.6001695  1711.        ]
 [  34.          147.1457959  3903.        ]
 [  25.          274.6148     2282.        ]
 [  44.          236.035       596.        ]
 [  30.          248.5451282  1158.        ]
 [  20.          109.8332161  1138.        ]
 [  21.          226.7211842  2023.        ]
 [  52.          418.7424675  3785.        ]
 [  69.          183.1394118  1043.        ]
 [  24.          100.4087742  1408.        ]
 [  23.          297.5103448  3903.        ]
 [  38.          304.3756044  3649.        ]
 [  46.          228.0211628  2470.        ]
 [  38.          157.5491803  2500.        ]
 [  19.          288.6292593  2854.        ]
 [  40.           74.46501931  892.        ]
 [  22.          268.9898374  3328.        ]
 [  20.          167.0059036  1395.        ]
 [  78.          318.9779412   782.        ]
 [  26.   

In [4]:
#Splitting the variable into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [11]:
#Applying Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
print(X_train)

[[-0.32058734 -0.0996204  -0.28543998]
 [-1.15599409  0.0997805   1.23727307]
 [-0.15350599 -1.32323429 -0.35965163]
 [ 0.93252278  0.34701623  0.17632138]
 [-0.82183139  0.41137855  0.68480859]
 [-0.98891274  0.10557095  0.47729083]
 [-1.15599409 -0.49661953 -0.26070277]
 [ 0.68190076  2.64727693  4.46891543]
 [-0.48766869 -1.61640266 -0.90593181]
 [-0.57120936 -1.04530364  2.5943842 ]
 [ 0.51481941  0.85269293 -0.3101772 ]
 [-1.07245341 -0.16121445  1.13076561]
 [-0.98891274 -0.58315483 -0.00783345]
 [ 0.26419738 -0.23942842 -1.10382953]
 [-0.15350599 -0.50976583  1.77187178]
 [-0.82183139 -0.28187165 -0.07792223]
 [ 0.68190076  0.6136071  -0.26482564]
 [-0.40412801 -1.12477518  0.34948189]
 [ 2.68687695 -0.93670551 -1.20621412]
 [-0.06996532 -0.39623945  0.38109055]
 [-1.07245341 -1.1244862  -0.92173614]
 [-0.32058734 -0.18890698  1.18367577]
 [-0.82183139  0.37642415  0.59341832]
 [ 1.18314481  0.0399105   0.09523828]
 [ 0.93252278 -0.5178337  -0.86813884]
 [-1.07245341 -0.02508888

In [13]:
# Training the Dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [22]:
# Comparing the acquired test results with the origninal test set
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1711. 1681.]
 [3578. 3517.]
 [1640. 1560.]
 [2718. 2687.]
 [1626. 1636.]
 [2887. 2854.]
 [ 996. 1002.]
 [2500. 2538.]
 [ 725.  664.]
 [1395. 1396.]
 [2588. 2572.]
 [1630. 1541.]
 [2588. 2544.]
 [ 916.  862.]
 [ 917.  920.]
 [2282. 2280.]
 [2470. 2485.]
 [4910. 5103.]
 [1640. 1537.]
 [3676. 3785.]]


In [24]:
#Obtainin the R-Squared Score
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9961120479702116